# Generated by Django 4.1.3 on 2022-11-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZeroFoodWaste', '0003_recipe_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
    ]
