# Generated by Django 4.1.3 on 2022-11-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZeroFoodWaste', '0005_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=dict),
        ),
    ]
