# Generated by Django 4.1.3 on 2022-11-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZeroFoodWaste', '0007_recipe_desiredcalories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mealTime',
            field=models.CharField(default='Breakfast', max_length=1000),
            preserve_default=False,
        ),
    ]
