# Generated by Django 4.1.3 on 2022-11-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZeroFoodWaste', '0009_remove_recipe_mealtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mealTime',
            field=models.CharField(default='Breakfast', max_length=1000),
            preserve_default=False,
        ),
    ]
